name: .NET Build
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Build project
      run: dotnet build -c release LibConf/LibConf.csproj
    - name: Prepare artifact
      if: contains(github.ref, 'refs/tags/') == false
      shell: bash
      run: |
        find "LibConf/bin/Release/netstandard2.0" -type f ! -name "LibConf.*" -delete
        find "LibConf/bin/Release/netstandard2.0" -type f -name "*.deps.json" -delete
        cp "LICENSE" "LibConf/bin/Release/netstandard2.0/LICENSE.LibConf.txt"
    - name: Upload DLLs
      if: contains(github.ref, 'refs/tags/') == false
      uses: actions/upload-artifact@v2
      with:
        name: LibConf
        path: ./LibConf/bin/Release/netstandard2.0/
