name: .NET Build
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    # Set Path workaround for https://github.com/actions/virtual-environments/issues/263
    - name: "Temp step to Set Path for Windows"
      run: |
        echo "::add-path::C:\Program Files\Git\mingw64\bin"
        echo "::add-path::C:\Program Files\Git\usr\bin"
        echo "::add-path::C:\Program Files\Git\bin"
    - name: Setup MSBuild
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Install dependencies
      run: msbuild -t:restore
    - name: Build project
      run: msbuild LibConf/LibConf.csproj /t:Build /p:Configuration=Release
    - name: Prepare artifact
      if: contains(github.ref, 'refs/tags/') == false
      shell: bash
      run: |
        find "LibConf/bin/Release/netstandard2.0" -type f ! -name "LibConf.*" -delete
        find "LibConf/bin/Release/netstandard2.0" -type f -name "*.deps.json" -delete
        cp "LICENSE" "LibConf/bin/Release/netstandard2.0/LICENSE.LibConf.txt"
    - name: Upload DLLs
      if: contains(github.ref, 'refs/tags/') == false
      uses: actions/upload-artifact@v1
      with:
        name: LibConf-${{ github.sha }}
        path: ./LibConf/bin/Release/netstandard2.0
